
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vcontainer;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Entry entry;

	private global::Gtk.Label lblErr;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Button btnABrack;

	private global::Gtk.Button btnCBrack;

	private global::Gtk.Button btnBackspace;

	private global::Gtk.Button btnC;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Button btn7;

	private global::Gtk.Button btn8;

	private global::Gtk.Button btn9;

	private global::Gtk.Button btnDIv;

	private global::Gtk.Button btnPercetage;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Button btn4;

	private global::Gtk.Button btn5;

	private global::Gtk.Button btn6;

	private global::Gtk.Button addMult;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button btn1;

	private global::Gtk.Button btn2;

	private global::Gtk.Button btn3;

	private global::Gtk.Button btnMinus;

	private global::Gtk.Button btnSqrt;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Button btnZero;

	private global::Gtk.Button btnPoint;

	private global::Gtk.Button btnAdd;

	private global::Gtk.Button btnEqual;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("XRF-5030 Titanium");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vcontainer = new global::Gtk.VBox();
		this.vcontainer.Name = "vcontainer";
		this.vcontainer.Spacing = 6;
		this.vcontainer.BorderWidth = ((uint)(10));
		// Container child vcontainer.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.entry = new global::Gtk.Entry();
		this.entry.CanFocus = true;
		this.entry.Name = "entry";
		this.entry.IsEditable = true;
		this.entry.InvisibleChar = '•';
		this.hbox3.Add(this.entry);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.entry]));
		w1.Position = 0;
		this.vcontainer.Add(this.hbox3);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vcontainer[this.hbox3]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vcontainer.Gtk.Box+BoxChild
		this.lblErr = new global::Gtk.Label();
		this.lblErr.Name = "lblErr";
		this.vcontainer.Add(this.lblErr);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vcontainer[this.lblErr]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vcontainer.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btnABrack = new global::Gtk.Button();
		this.btnABrack.WidthRequest = 51;
		this.btnABrack.CanFocus = true;
		this.btnABrack.Name = "btnABrack";
		this.btnABrack.UseUnderline = true;
		this.btnABrack.Label = global::Mono.Unix.Catalog.GetString("(");
		this.hbox4.Add(this.btnABrack);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btnABrack]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btnCBrack = new global::Gtk.Button();
		this.btnCBrack.WidthRequest = 51;
		this.btnCBrack.CanFocus = true;
		this.btnCBrack.Name = "btnCBrack";
		this.btnCBrack.UseUnderline = true;
		this.btnCBrack.Label = global::Mono.Unix.Catalog.GetString(")");
		this.hbox4.Add(this.btnCBrack);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btnCBrack]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btnBackspace = new global::Gtk.Button();
		this.btnBackspace.WidthRequest = 80;
		this.btnBackspace.CanFocus = true;
		this.btnBackspace.Name = "btnBackspace";
		this.btnBackspace.UseUnderline = true;
		this.btnBackspace.Label = global::Mono.Unix.Catalog.GetString("Backspace");
		this.hbox4.Add(this.btnBackspace);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btnBackspace]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btnC = new global::Gtk.Button();
		this.btnC.WidthRequest = 80;
		this.btnC.HeightRequest = 36;
		this.btnC.CanDefault = true;
		this.btnC.CanFocus = true;
		this.btnC.Name = "btnC";
		this.btnC.UseUnderline = true;
		this.btnC.Label = "C";
		this.hbox4.Add(this.btnC);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btnC]));
		w7.Position = 3;
		w7.Expand = false;
		w7.Fill = false;
		this.vcontainer.Add(this.hbox4);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vcontainer[this.hbox4]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vcontainer.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.btn7 = new global::Gtk.Button();
		this.btn7.WidthRequest = 51;
		this.btn7.HeightRequest = 36;
		this.btn7.CanDefault = true;
		this.btn7.CanFocus = true;
		this.btn7.Name = "btn7";
		this.btn7.UseUnderline = true;
		this.btn7.Label = "7";
		this.hbox5.Add(this.btn7);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.btn7]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.btn8 = new global::Gtk.Button();
		this.btn8.WidthRequest = 51;
		this.btn8.HeightRequest = 36;
		this.btn8.CanDefault = true;
		this.btn8.CanFocus = true;
		this.btn8.Name = "btn8";
		this.btn8.UseUnderline = true;
		this.btn8.Label = "8";
		this.hbox5.Add(this.btn8);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.btn8]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.btn9 = new global::Gtk.Button();
		this.btn9.WidthRequest = 51;
		this.btn9.HeightRequest = 36;
		this.btn9.CanDefault = true;
		this.btn9.CanFocus = true;
		this.btn9.Name = "btn9";
		this.btn9.UseUnderline = true;
		this.btn9.Label = "9";
		this.hbox5.Add(this.btn9);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.btn9]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.btnDIv = new global::Gtk.Button();
		this.btnDIv.WidthRequest = 51;
		this.btnDIv.HeightRequest = 36;
		this.btnDIv.CanDefault = true;
		this.btnDIv.CanFocus = true;
		this.btnDIv.Name = "btnDIv";
		this.btnDIv.UseUnderline = true;
		this.btnDIv.Label = "/";
		this.hbox5.Add(this.btnDIv);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.btnDIv]));
		w12.Position = 3;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.btnPercetage = new global::Gtk.Button();
		this.btnPercetage.WidthRequest = 51;
		this.btnPercetage.HeightRequest = 36;
		this.btnPercetage.Sensitive = false;
		this.btnPercetage.CanDefault = true;
		this.btnPercetage.CanFocus = true;
		this.btnPercetage.Name = "btnPercetage";
		this.btnPercetage.UseUnderline = true;
		this.hbox5.Add(this.btnPercetage);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.btnPercetage]));
		w13.Position = 4;
		w13.Expand = false;
		w13.Fill = false;
		this.vcontainer.Add(this.hbox5);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vcontainer[this.hbox5]));
		w14.Position = 3;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vcontainer.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.btn4 = new global::Gtk.Button();
		this.btn4.WidthRequest = 51;
		this.btn4.HeightRequest = 36;
		this.btn4.CanDefault = true;
		this.btn4.CanFocus = true;
		this.btn4.Name = "btn4";
		this.btn4.UseUnderline = true;
		this.btn4.Label = "4";
		this.hbox6.Add(this.btn4);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.btn4]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.btn5 = new global::Gtk.Button();
		this.btn5.WidthRequest = 51;
		this.btn5.HeightRequest = 36;
		this.btn5.CanDefault = true;
		this.btn5.CanFocus = true;
		this.btn5.Name = "btn5";
		this.btn5.UseUnderline = true;
		this.btn5.Label = "5";
		this.hbox6.Add(this.btn5);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.btn5]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.btn6 = new global::Gtk.Button();
		this.btn6.WidthRequest = 51;
		this.btn6.HeightRequest = 36;
		this.btn6.CanDefault = true;
		this.btn6.CanFocus = true;
		this.btn6.Name = "btn6";
		this.btn6.UseUnderline = true;
		this.btn6.Label = "6";
		this.hbox6.Add(this.btn6);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.btn6]));
		w17.Position = 2;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.addMult = new global::Gtk.Button();
		this.addMult.WidthRequest = 51;
		this.addMult.HeightRequest = 36;
		this.addMult.CanDefault = true;
		this.addMult.CanFocus = true;
		this.addMult.Name = "addMult";
		this.addMult.UseUnderline = true;
		this.addMult.Label = "*";
		this.hbox6.Add(this.addMult);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.addMult]));
		w18.Position = 3;
		w18.Expand = false;
		w18.Fill = false;
		this.vcontainer.Add(this.hbox6);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vcontainer[this.hbox6]));
		w19.Position = 4;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vcontainer.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btn1 = new global::Gtk.Button();
		this.btn1.WidthRequest = 51;
		this.btn1.HeightRequest = 36;
		this.btn1.CanDefault = true;
		this.btn1.CanFocus = true;
		this.btn1.Name = "btn1";
		this.btn1.UseUnderline = true;
		this.btn1.Label = "1";
		this.hbox1.Add(this.btn1);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btn1]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btn2 = new global::Gtk.Button();
		this.btn2.WidthRequest = 51;
		this.btn2.HeightRequest = 36;
		this.btn2.CanDefault = true;
		this.btn2.CanFocus = true;
		this.btn2.Name = "btn2";
		this.btn2.UseUnderline = true;
		this.btn2.Label = "2";
		this.hbox1.Add(this.btn2);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btn2]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btn3 = new global::Gtk.Button();
		this.btn3.WidthRequest = 51;
		this.btn3.HeightRequest = 36;
		this.btn3.CanDefault = true;
		this.btn3.CanFocus = true;
		this.btn3.Name = "btn3";
		this.btn3.UseUnderline = true;
		this.btn3.Label = "3";
		this.hbox1.Add(this.btn3);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btn3]));
		w22.Position = 2;
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnMinus = new global::Gtk.Button();
		this.btnMinus.WidthRequest = 51;
		this.btnMinus.HeightRequest = 36;
		this.btnMinus.CanDefault = true;
		this.btnMinus.CanFocus = true;
		this.btnMinus.Name = "btnMinus";
		this.btnMinus.UseUnderline = true;
		this.btnMinus.Label = "-";
		this.hbox1.Add(this.btnMinus);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnMinus]));
		w23.Position = 3;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnSqrt = new global::Gtk.Button();
		this.btnSqrt.WidthRequest = 51;
		this.btnSqrt.HeightRequest = 36;
		this.btnSqrt.CanDefault = true;
		this.btnSqrt.CanFocus = true;
		this.btnSqrt.Name = "btnSqrt";
		this.btnSqrt.UseUnderline = true;
		this.btnSqrt.Label = "sqrt";
		this.hbox1.Add(this.btnSqrt);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnSqrt]));
		w24.Position = 4;
		w24.Expand = false;
		w24.Fill = false;
		this.vcontainer.Add(this.hbox1);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vcontainer[this.hbox1]));
		w25.Position = 5;
		w25.Expand = false;
		w25.Fill = false;
		// Container child vcontainer.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnZero = new global::Gtk.Button();
		this.btnZero.WidthRequest = 51;
		this.btnZero.HeightRequest = 36;
		this.btnZero.CanDefault = true;
		this.btnZero.CanFocus = true;
		this.btnZero.Name = "btnZero";
		this.btnZero.UseUnderline = true;
		this.btnZero.Label = "0";
		this.hbox2.Add(this.btnZero);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnZero]));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnPoint = new global::Gtk.Button();
		this.btnPoint.WidthRequest = 51;
		this.btnPoint.HeightRequest = 36;
		this.btnPoint.CanDefault = true;
		this.btnPoint.CanFocus = true;
		this.btnPoint.Name = "btnPoint";
		this.btnPoint.UseUnderline = true;
		this.btnPoint.Label = ".";
		this.hbox2.Add(this.btnPoint);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnPoint]));
		w27.Position = 1;
		w27.Expand = false;
		w27.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnAdd = new global::Gtk.Button();
		this.btnAdd.WidthRequest = 51;
		this.btnAdd.HeightRequest = 36;
		this.btnAdd.CanDefault = true;
		this.btnAdd.CanFocus = true;
		this.btnAdd.Name = "btnAdd";
		this.btnAdd.UseUnderline = true;
		this.btnAdd.Label = "+";
		this.hbox2.Add(this.btnAdd);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnAdd]));
		w28.Position = 2;
		w28.Expand = false;
		w28.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnEqual = new global::Gtk.Button();
		this.btnEqual.WidthRequest = 108;
		this.btnEqual.HeightRequest = 36;
		this.btnEqual.CanDefault = true;
		this.btnEqual.CanFocus = true;
		this.btnEqual.Name = "btnEqual";
		this.btnEqual.UseUnderline = true;
		this.btnEqual.Label = "=";
		this.hbox2.Add(this.btnEqual);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnEqual]));
		w29.Position = 3;
		w29.Expand = false;
		w29.Fill = false;
		this.vcontainer.Add(this.hbox2);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vcontainer[this.hbox2]));
		w30.Position = 6;
		w30.Expand = false;
		w30.Fill = false;
		this.Add(this.vcontainer);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 300;
		this.DefaultHeight = 293;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.entry.Changed += new global::System.EventHandler(this.OnEntryChanged);
		this.btnABrack.Clicked += new global::System.EventHandler(this.OnBtnCharClicked);
		this.btnCBrack.Clicked += new global::System.EventHandler(this.OnBtnCharClicked);
		this.btnBackspace.Clicked += new global::System.EventHandler(this.OnBtnBackspaceClicked);
		this.btnC.Clicked += new global::System.EventHandler(this.OnBtnCClicked);
		this.btn7.Clicked += new global::System.EventHandler(this.OnBtnCharClicked);
		this.btn8.Clicked += new global::System.EventHandler(this.OnBtnCharClicked);
		this.btn9.Clicked += new global::System.EventHandler(this.OnBtnCharClicked);
		this.btnDIv.Clicked += new global::System.EventHandler(this.OnBtnCharClicked);
		this.btn4.Clicked += new global::System.EventHandler(this.OnBtnCharClicked);
		this.btn5.Clicked += new global::System.EventHandler(this.OnBtnCharClicked);
		this.btn6.Clicked += new global::System.EventHandler(this.OnBtnCharClicked);
		this.addMult.Clicked += new global::System.EventHandler(this.OnBtnCharClicked);
		this.btn1.Clicked += new global::System.EventHandler(this.OnBtnCharClicked);
		this.btn2.Clicked += new global::System.EventHandler(this.OnBtnCharClicked);
		this.btn3.Clicked += new global::System.EventHandler(this.OnBtnCharClicked);
		this.btnMinus.Clicked += new global::System.EventHandler(this.OnBtnCharClicked);
		this.btnSqrt.Clicked += new global::System.EventHandler(this.OnBtnSqrtClicked);
		this.btnZero.Clicked += new global::System.EventHandler(this.OnBtnCharClicked);
		this.btnPoint.Clicked += new global::System.EventHandler(this.OnBtnCharClicked);
		this.btnAdd.Clicked += new global::System.EventHandler(this.OnBtnCharClicked);
		this.btnEqual.Clicked += new global::System.EventHandler(this.OnBtnEqualClicked);
	}
}
